name: Test Pull Request

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry==1.5.1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint
        run: |
          poetry run black --check .
          poetry run isort --check-only .
          poetry run mypy .
